### PR TITLE
Update full_text_and_vector_search.ipynb

### PR DESCRIPTION
**Pull request by arbkz**
fixed typo railword -> railroad

## Checklist

 - [ ] Link to issue this PR refers to (if applicable): 
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by arbkz** [comment]
@cla-bot](https://github.com/cla-bot) check

**Comment by arbkz** [comment]
@cla-bot check

**Comment by arbkz** [comment]
@cla-bot check

**Comment by simonprickett** [comment]
@arbkz thank you!  Are you having trouble with the CLA step?  I'll summon the bot now and see if it finds you.  If it doesn't, it could be because the email address used on your commit differs to that used with the cla bot.

@cla-bot check

**Pull request closed without merging**
